name: create and push a docker image to docker hub

on:
  push:
    branches: ["main"]

env:
  IMAGE_NAME: ${{github.repository}}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    environment: Docker Deploy
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - name: "Log into docker"
        uses: docker/login-action@v3
        with:
          username: crystalkey
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: "Build & Push"
        id: push
        uses: docker/build-push-action@v6
        with: 
          context: ./ltzf_ap
          push: true
          tags: crystalkey/ltzf-ap:0.1.0